/*
 ==============================================================================
 
 This file was auto-generated by the Jucer!
 
 It contains the basic startup code for a Juce application.
 
 ==============================================================================
 */

#include "PluginProcessor.h"
#include "PluginEditor.h"
#include "Envelope.h"

//==============================================================================
// This is a handy slider subclass that controls an AudioProcessorParameter
// (may move this class into the library itself at some point in the future..)
class WavelandSynthAudioProcessorEditor::ParameterSlider   : public Slider,
                                                             private Timer
{
public:
    ParameterSlider (AudioProcessorParameter& p)
    : Slider (p.getName (256)), param (p)
    {
        setRange (0.0, 1.0, 0.0);
        startTimerHz (30);
        updateSliderPos();
        Slider::setSliderStyle(Slider::Rotary);
        Slider::setTextBoxStyle(Slider::TextBoxBelow, false, 50, this->getTextBoxHeight());
        
    }
    
    void valueChanged() override
    {
        param.setValue ((float) Slider::getValue());
    }
    
    void timerCallback() override       { updateSliderPos(); }
    
    void startedDragging() override     { param.beginChangeGesture(); }
    void stoppedDragging() override     { param.endChangeGesture();   }
    
    double getValueFromText (const String& text) override   { return param.getValueForText (text); }
    String getTextFromValue (double value) override         { return param.getText ((float) value, 1024); }
    
    void updateSliderPos()
    {
        const float newValue = param.getValue();
        
        if (newValue != (float) Slider::getValue())
            Slider::setValue (newValue);
    }
    
    void makeParamSlider (ScopedPointer<ParameterSlider> newSlider, AudioProcessorParameter& param)
    {
        addAndMakeVisible(newSlider = new ParameterSlider (param));
        newSlider->setSliderStyle (Slider::Rotary);
        newSlider->setTextBoxStyle (Slider::TextBoxBelow, false, 50, newSlider->getTextBoxHeight());
    }
    
    AudioProcessorParameter& param;
    
    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (ParameterSlider)
};

//==============================================================================
WavelandSynthAudioProcessorEditor::WavelandSynthAudioProcessorEditor (WavelandSynthAudioProcessor& owner)
    : AudioProcessorEditor (owner),
      midiKeyboard (owner.keyboardState, MidiKeyboardComponent::horizontalKeyboard),
      timecodeDisplayLabel (String::empty),
      bendAmountLabel (String::empty, "Bend Amount:"),
      detuneLabel (String::empty, "Detune:"),
      balanceLabel (String::empty, "OSC Balance:"),
      cutoffLabel (String::empty, "Cutoff:"),
      resonaceLabel ( String::empty, "Resonace:"),
      keytrackLabel ( String::empty, "Keytracking:"),
      filEnvAmtLabel (String::empty, "Filter EnvAmt:"),
      lfoRateLabel (String::empty, "Lfo Rate:"),
      vibratoAmtLabel (String::empty, "Vibrato Amt:"),

      volAttackLabel ( String::empty, "Attack:"),
      volDecayLabel ( String::empty, "Decay:"),
      volSustainLabel ( String::empty, "Sustain:"),
      volReleaseLabel ( String::empty, "Release:"),

      filAttackLabel ( String::empty, "FAttack:"),
      filDecayLabel ( String::empty, "FDecay:"),
      filSustainLabel ( String::empty, "FSustain:"),
      filReleaseLabel ( String::empty, "FRelease:")
{
    // add some sliders...
    
    addAndMakeVisible (bendAmountSlider = new ParameterSlider (*owner.bendAmountParam));
    
    addAndMakeVisible (detuneSlider = new ParameterSlider(*owner.detuneParam));
    
    addAndMakeVisible (balanceSlider = new ParameterSlider(*owner.balanceParam));
    
    addAndMakeVisible (cutoffSlider = new ParameterSlider (*owner.cutoffKnobParam));
    
    addAndMakeVisible (resonaceSlider = new ParameterSlider (*owner.resonaceParam));
    
    addAndMakeVisible (keytrackSlider = new ParameterSlider (*owner.keytrackParam));
    
    addAndMakeVisible (filEnvAmtSlider = new ParameterSlider (*owner.filEnvAmtParam));
    
    addAndMakeVisible (lfoRateSlider = new ParameterSlider (*owner.lfoRateParam));
    
    addAndMakeVisible (vibratoAmtSlider = new ParameterSlider (*owner.vibratoAmtParam));
    
    
    addAndMakeVisible (volAttackSlider = new ParameterSlider (*owner.volEnvAttParam));
    
    addAndMakeVisible (volDecaySlider = new ParameterSlider (*owner.volEnvDecParam));

    addAndMakeVisible (volSustainSlider = new ParameterSlider (*owner.volEnvSusParam));

    addAndMakeVisible (volReleaseSlider = new ParameterSlider (*owner.volEnvRelParam));
    
    
    addAndMakeVisible (filAttackSlider = new ParameterSlider (*owner.filEnvAttParam));

    addAndMakeVisible (filDecaySlider = new ParameterSlider (*owner.filEnvDecParam));

    addAndMakeVisible (filSustainSlider = new ParameterSlider (*owner.filEnvSusParam));

    addAndMakeVisible (filReleaseSlider = new ParameterSlider (*owner.filEnvRelParam));

    // add some labels for the sliders...
    
    bendAmountLabel.attachToComponent(bendAmountSlider, false);
    bendAmountLabel.setFont (Font (11.0f));
    bendAmountLabel.setJustificationType(Justification::centredTop);
    
    detuneLabel.attachToComponent(detuneSlider, false);
    detuneLabel.setFont(Font (11.0f));
    detuneLabel.setJustificationType(Justification::centredTop);
    
    balanceLabel.attachToComponent(balanceSlider, false);
    balanceLabel.setFont(Font (11.0f));
    balanceLabel.setJustificationType(Justification::centredTop);
    
    cutoffLabel.attachToComponent(cutoffSlider, false);
    cutoffLabel.setFont (Font (11.0f));
    cutoffLabel.setJustificationType(Justification::centredTop);
    
    resonaceLabel.attachToComponent(resonaceSlider, false);
    resonaceLabel.setFont (Font (11.0f));
    resonaceLabel.setJustificationType(Justification::centredTop);
    
    keytrackLabel.attachToComponent(keytrackSlider, false);
    keytrackLabel.setFont (Font (11.0f));
    keytrackLabel.setJustificationType(Justification::centredTop);
    
    filEnvAmtLabel.attachToComponent(filEnvAmtSlider, false);
    filEnvAmtLabel.setFont (Font (11.0f));
    filEnvAmtLabel.setJustificationType(Justification::centredTop);
    
    lfoRateLabel.attachToComponent(lfoRateSlider, false);
    lfoRateLabel.setFont (Font (11.0f));
    lfoRateLabel.setJustificationType(Justification::centredTop);
    
    vibratoAmtLabel.attachToComponent(vibratoAmtSlider, false);
    vibratoAmtLabel.setFont (Font (11.0f));
    vibratoAmtLabel.setJustificationType(Justification::centredTop);
    
    
    volAttackLabel.attachToComponent(volAttackSlider, false);
    volAttackLabel.setFont (Font (11.0f));
    volAttackLabel.setJustificationType(Justification::centredTop);
    
    volDecayLabel.attachToComponent(volDecaySlider, false);
    volDecayLabel.setFont (Font (11.0f));
    volDecayLabel.setJustificationType(Justification::centredTop);
    
    volSustainLabel.attachToComponent(volSustainSlider, false);
    volSustainLabel.setFont (Font (11.0f));
    volSustainLabel.setJustificationType(Justification::centredTop);
    
    volReleaseLabel.attachToComponent(volReleaseSlider, false);
    volReleaseLabel.setFont (Font (11.0f));
    volReleaseLabel.setJustificationType(Justification::centredTop);
    
    
    filAttackLabel.attachToComponent(filAttackSlider, false);
    filAttackLabel.setFont (Font (11.0f));
    filAttackLabel.setJustificationType(Justification::centredTop);
    
    filDecayLabel.attachToComponent(filDecaySlider, false);
    filDecayLabel.setFont (Font (11.0f));
    filDecayLabel.setJustificationType(Justification::centredTop);
    
    filSustainLabel.attachToComponent(filSustainSlider, false);
    filSustainLabel.setFont (Font (11.0f));
    filSustainLabel.setJustificationType(Justification::centredTop);
    
    filReleaseLabel.attachToComponent(filReleaseSlider, false);
    filReleaseLabel.setFont (Font (11.0f));
    filReleaseLabel.setJustificationType(Justification::centredTop);
    
    // add the midi keyboard component..
    addAndMakeVisible (midiKeyboard);
    
    // add a label that will display the current timecode and status..
    addAndMakeVisible (timecodeDisplayLabel);
    timecodeDisplayLabel.setColour (Label::textColourId, Colours::blue);
    timecodeDisplayLabel.setFont (Font (Font::getDefaultMonospacedFontName(), 15.0f, Font::plain));
    
    // add the triangular resizer component for the bottom-right of the UI
    addAndMakeVisible (resizer = new ResizableCornerComponent (this, &resizeLimits));
    resizeLimits.setSizeLimits (400, 400, 2000, 1000);
 
    
    // set our component's initial size to be the last one that was stored in the filter's settings
    setSize (owner.lastUIWidth,
             owner.lastUIHeight);
    
    // start a timer which will keep our timecode display updated
    startTimerHz (30);
}

WavelandSynthAudioProcessorEditor::~WavelandSynthAudioProcessorEditor()
{
}

//==============================================================================
//void WavelandSynthAudioProcessorEditor::setupLabel(Label& labelToUse, juce::Component *sliderToUse);


void WavelandSynthAudioProcessorEditor::paint (Graphics& g)
{
    g.setGradientFill (ColourGradient (Colours::darkgrey, 0, 0,
                                       Colours::lightgrey, 0, (float) getHeight(), false));
    g.fillAll();
}

void WavelandSynthAudioProcessorEditor::resized()
{
    // This lays out our child components...
    
    Rectangle<int> r (getLocalBounds().reduced (8));
    
    timecodeDisplayLabel.setBounds (r.removeFromTop (26));
    midiKeyboard.setBounds (r.removeFromBottom (70));
    int sliderXY = 50;
    int defaultsliderDistance = 60;
    int divider = 10;
    
    r.removeFromTop (30);
    Rectangle<int> sliderArea;
    sliderArea.setBounds(r.getX() + 8, r.getY() + 26, r.getWidth() - 16, (r.getHeight() - 100) / 4);
    
    bendAmountSlider->setBounds (sliderArea.removeFromLeft (jmin (defaultsliderDistance, sliderArea.getWidth()/ divider * 1)));
    bendAmountSlider->setSize(sliderXY, sliderXY);
    
    detuneSlider->setBounds (sliderArea.removeFromLeft (jmin (defaultsliderDistance, sliderArea.getWidth() / divider * 2)));
    detuneSlider->setSize(sliderXY, sliderXY);
    
    balanceSlider->setBounds (sliderArea.removeFromLeft (jmin (defaultsliderDistance, sliderArea.getWidth() / divider * 3)));
    balanceSlider->setSize(sliderXY, sliderXY);
    
    cutoffSlider->setBounds (sliderArea.removeFromLeft (jmin (defaultsliderDistance, sliderArea.getWidth() / divider * 4)));
    cutoffSlider->setSize(sliderXY, sliderXY);
    
    resonaceSlider->setBounds(sliderArea.removeFromLeft(jmin (defaultsliderDistance, sliderArea.getWidth() / divider * 5)));
    resonaceSlider->setSize(sliderXY, sliderXY);
    
    keytrackSlider->setBounds(sliderArea.removeFromLeft(jmin (defaultsliderDistance, sliderArea.getWidth() / divider * 6)));
    keytrackSlider->setSize(sliderXY, sliderXY);
    
    filEnvAmtSlider->setBounds(sliderArea.removeFromLeft(jmin (defaultsliderDistance, sliderArea.getWidth() / divider * 7)));
    filEnvAmtSlider->setSize(sliderXY, sliderXY);
    
    lfoRateSlider->setBounds(sliderArea.removeFromLeft(jmin (defaultsliderDistance, sliderArea.getWidth() / divider * 8)));
    lfoRateSlider->setSize(sliderXY, sliderXY);
    
    vibratoAmtSlider->setBounds(sliderArea.removeFromLeft(jmin (defaultsliderDistance, sliderArea.getWidth() / divider * 9)));
    vibratoAmtSlider->setSize(sliderXY, sliderXY);
    
    
    Rectangle<int> sliderRow2;
    sliderRow2.setBounds(r.getX() + 8 , r.getY() + 150, r.getWidth() - 16, r.getHeight() /4);
    
    volAttackSlider->setBounds (sliderRow2.removeFromLeft (jmin (defaultsliderDistance, sliderRow2.getWidth()/ divider * 1)));
    volAttackSlider->setSize(sliderXY, sliderXY);
    
    volDecaySlider->setBounds (sliderRow2.removeFromLeft (jmin (defaultsliderDistance, sliderRow2.getWidth()/ divider * 2)));
    volDecaySlider->setSize(sliderXY, sliderXY);
    
    volSustainSlider->setBounds (sliderRow2.removeFromLeft (jmin (defaultsliderDistance, sliderRow2.getWidth()/ divider * 3)));
    volSustainSlider->setSize(sliderXY, sliderXY);
    
    volReleaseSlider->setBounds (sliderRow2.removeFromLeft (jmin (defaultsliderDistance, sliderRow2.getWidth()/ divider * 4)));
    volReleaseSlider->setSize(sliderXY, sliderXY);
    
    filAttackSlider->setBounds (sliderRow2.removeFromLeft (jmin (defaultsliderDistance, sliderRow2.getWidth()/ divider * 5)));
    filAttackSlider->setSize(sliderXY, sliderXY);
    
    filDecaySlider->setBounds (sliderRow2.removeFromLeft (jmin (defaultsliderDistance, sliderRow2.getWidth()/ divider * 6)));
    filDecaySlider->setSize(sliderXY, sliderXY);
    
    filSustainSlider->setBounds (sliderRow2.removeFromLeft (jmin (defaultsliderDistance, sliderRow2.getWidth()/ divider * 7)));
    filSustainSlider->setSize(sliderXY, sliderXY);
    
    filReleaseSlider->setBounds (sliderRow2.removeFromLeft (jmin (defaultsliderDistance, sliderRow2.getWidth()/ divider * 8)));
    filReleaseSlider->setSize(sliderXY, sliderXY);
    
    
    resizer->setBounds (getWidth() - 16, getHeight() - 16, 16, 16);
    
    getProcessor().lastUIWidth = getWidth();
    getProcessor().lastUIHeight = getHeight();
}

//==============================================================================
void WavelandSynthAudioProcessorEditor::timerCallback()
{
    updateTimecodeDisplay (getProcessor().lastPosInfo);
}

//==============================================================================
// quick-and-dirty function to format a timecode string
static String timeToTimecodeString (double seconds)
{
    const int millisecs = roundToInt (std::abs (seconds * 1000.0));
    
    return String::formatted ("%s%02d:%02d:%02d.%03d",
                              seconds < 0 ? "-" : "",
                              millisecs / 360000,
                              (millisecs / 60000) % 60,
                              (millisecs / 1000) % 60,
                              millisecs % 1000);
}

// quick-and-dirty function to format a bars/beats string
static String quarterNotePositionToBarsBeatsString (double quarterNotes, int numerator, int denominator)
{
    if (numerator == 0 || denominator == 0)
        return "1|1|000";
    
    const int quarterNotesPerBar = (numerator * 4 / denominator);
    const double beats  = (fmod (quarterNotes, quarterNotesPerBar) / quarterNotesPerBar) * numerator;
    
    const int bar    = ((int) quarterNotes) / quarterNotesPerBar + 1;
    const int beat   = ((int) beats) + 1;
    const int ticks  = ((int) (fmod (beats, 1.0) * 960.0 + 0.5));
    
    return String::formatted ("%d|%d|%03d", bar, beat, ticks);
}

// Updates the text in our position label.
void WavelandSynthAudioProcessorEditor::updateTimecodeDisplay (AudioPlayHead::CurrentPositionInfo pos)
{
    if (lastDisplayedPosition != pos)
    {
        lastDisplayedPosition = pos;
        
        MemoryOutputStream displayText;
        
        displayText << "[" << SystemStats::getJUCEVersion() << "]   "
        << String (pos.bpm, 2) << " bpm, "
        << pos.timeSigNumerator << '/' << pos.timeSigDenominator
        << "  -  " << timeToTimecodeString (pos.timeInSeconds)
        << "  -  " << quarterNotePositionToBarsBeatsString (pos.ppqPosition,
                                                            pos.timeSigNumerator,
                                                            pos.timeSigDenominator);
        
        if (pos.isRecording)
            displayText << "  (recording)";
        else if (pos.isPlaying)
            displayText << "  (playing)";
        
        timecodeDisplayLabel.setText (displayText.toString(), dontSendNotification);
    }
}
