/*
 ==============================================================================
 
 This file was auto-generated by the Jucer!
 
 It contains the basic startup code for a Juce application.
 
 ==============================================================================
 */

#include "PluginProcessor.h"
#include "PluginEditor.h"

//==============================================================================
// This is a handy slider subclass that controls an AudioProcessorParameter
// (may move this class into the library itself at some point in the future..)
class WavelandSynthAudioProcessorEditor::ParameterSlider   : public Slider,
                                                             private Timer
{
public:
    ParameterSlider (AudioProcessorParameter& p)
    : Slider (p.getName (256)), param (p)
    {
        setRange (0.0, 1.0, 0.0);
        startTimerHz (30);
        updateSliderPos();
    }
    
    void valueChanged() override
    {
        param.setValue ((float) Slider::getValue());
    }
    
    void timerCallback() override       { updateSliderPos(); }
    
    void startedDragging() override     { param.beginChangeGesture(); }
    void stoppedDragging() override     { param.endChangeGesture();   }
    
    double getValueFromText (const String& text) override   { return param.getValueForText (text); }
    String getTextFromValue (double value) override         { return param.getText ((float) value, 1024); }
    
    void updateSliderPos()
    {
        const float newValue = param.getValue();
        
        if (newValue != (float) Slider::getValue())
            Slider::setValue (newValue);
    }
    
    AudioProcessorParameter& param;
    
    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (ParameterSlider)
};

//==============================================================================
WavelandSynthAudioProcessorEditor::WavelandSynthAudioProcessorEditor (WavelandSynthAudioProcessor& owner)
    : AudioProcessorEditor (owner),
      midiKeyboard (owner.keyboardState, MidiKeyboardComponent::horizontalKeyboard),
      timecodeDisplayLabel (String::empty),
      bendAmountLabel (String::empty, "Bend Amount:"),
      detuneLabel (String::empty, "Detune:"),
      balanceLabel (String::empty, "OSC Balance:"),
      cutoffLabel (String::empty, "Cutoff:"),
      resonaceLabel ( String::empty, "Resonace:"),
      keytrackLabel ( String::empty, "Keytracking:")
{
    // add some sliders..
    
    addAndMakeVisible (bendAmountSlider = new ParameterSlider (*owner.bendAmountParam));
    bendAmountSlider->setSliderStyle (Slider::Rotary);
    bendAmountSlider->setTextBoxStyle (Slider::TextBoxBelow, false, 50, bendAmountSlider->getTextBoxHeight());
    
    addAndMakeVisible(detuneSlider = new ParameterSlider(*owner.detuneParam));
    detuneSlider->setSliderStyle (Slider::Rotary);
    detuneSlider->setTextBoxStyle (Slider::TextBoxBelow, false, 50, detuneSlider->getTextBoxHeight());
    
    addAndMakeVisible(balanceSlider = new ParameterSlider(*owner.balanceParam));
    balanceSlider->setSliderStyle (Slider::Rotary);
    balanceSlider->setTextBoxStyle (Slider::TextBoxBelow, false, 50, balanceSlider->getTextBoxHeight());
    
    addAndMakeVisible (cutoffSlider = new ParameterSlider (*owner.cutoffKnobParam));
    cutoffSlider->setSliderStyle (Slider::Rotary);
    cutoffSlider->setTextBoxStyle (Slider::TextBoxBelow, false, 50, cutoffSlider->getTextBoxHeight());
    
    addAndMakeVisible (resonaceSlider = new ParameterSlider (*owner.resonaceParam));
    resonaceSlider->setSliderStyle (Slider::Rotary);
    resonaceSlider->setTextBoxStyle (Slider::TextBoxBelow, false, 50, resonaceSlider->getTextBoxHeight());
    
    addAndMakeVisible (keytrackSlider = new ParameterSlider (*owner.keytrackParam));
    keytrackSlider->setSliderStyle (Slider::Rotary);
    keytrackSlider->setTextBoxStyle (Slider::TextBoxBelow, false, 50, resonaceSlider->getTextBoxHeight());
    
    // add some labels for the sliders..
    
    bendAmountLabel.attachToComponent(bendAmountSlider, false);
    bendAmountLabel.setFont (Font (11.0f));
    bendAmountLabel.setJustificationType(Justification::centred);
    
    detuneLabel.attachToComponent(detuneSlider, false);
    detuneLabel.setFont(Font (11.0f));
    detuneLabel.setJustificationType(Justification::centred);
    
    balanceLabel.attachToComponent(balanceSlider, false);
    balanceLabel.setFont(Font (11.0f));
    balanceLabel.setJustificationType(Justification::centred);
    
    cutoffLabel.attachToComponent(cutoffSlider, false);
    cutoffLabel.setFont (Font (11.0f));
    cutoffLabel.setJustificationType(Justification::centred);
    
    resonaceLabel.attachToComponent(resonaceSlider, false);
    resonaceLabel.setFont (Font (11.0f));
    resonaceLabel.setJustificationType(Justification::centred);
    
    keytrackLabel.attachToComponent(keytrackSlider, false);
    keytrackLabel.setFont (Font (11.0f));
    keytrackLabel.setJustificationType(Justification::centred);
    
    // add the midi keyboard component..
    addAndMakeVisible (midiKeyboard);
    
    // add a label that will display the current timecode and status..
    addAndMakeVisible (timecodeDisplayLabel);
    timecodeDisplayLabel.setColour (Label::textColourId, Colours::blue);
    timecodeDisplayLabel.setFont (Font (Font::getDefaultMonospacedFontName(), 15.0f, Font::plain));
    
    // add the triangular resizer component for the bottom-right of the UI
    addAndMakeVisible (resizer = new ResizableCornerComponent (this, &resizeLimits));
    resizeLimits.setSizeLimits (150, 150, 8000, 300);
    
    // set our component's initial size to be the last one that was stored in the filter's settings
    setSize (owner.lastUIWidth,
             owner.lastUIHeight);
    
    // start a timer which will keep our timecode display updated
    startTimerHz (30);
}

WavelandSynthAudioProcessorEditor::~WavelandSynthAudioProcessorEditor()
{
}

//==============================================================================
void WavelandSynthAudioProcessorEditor::paint (Graphics& g)
{
    g.setGradientFill (ColourGradient (Colours::darkgrey, 0, 0,
                                       Colours::lightgrey, 0, (float) getHeight(), false));
    g.fillAll();
}

void WavelandSynthAudioProcessorEditor::resized()
{
    // This lays out our child components...
    
    Rectangle<int> r (getLocalBounds().reduced (8));
    
    timecodeDisplayLabel.setBounds (r.removeFromTop (26));
    midiKeyboard.setBounds (r.removeFromBottom (70));
    
    r.removeFromTop (30);
    Rectangle<int> sliderArea (r.removeFromTop (50));
    bendAmountSlider->setBounds (sliderArea.removeFromLeft (jmin (100, sliderArea.getWidth()/ 8 * 1)));
    detuneSlider->setBounds (sliderArea.removeFromLeft (jmin (100, sliderArea.getWidth() / 8 * 2)));
    balanceSlider->setBounds (sliderArea.removeFromLeft (jmin (100, sliderArea.getWidth() / 8 * 3)));
    cutoffSlider->setBounds (sliderArea.removeFromLeft (jmin (100, sliderArea.getWidth() / 8 * 4)));
    resonaceSlider->setBounds(sliderArea.removeFromLeft(jmin (100, sliderArea.getWidth() / 8 * 5)));
    keytrackSlider->setBounds(sliderArea.removeFromLeft(jmin (100, sliderArea.getWidth() / 8 * 6)));
    
    resizer->setBounds (getWidth() - 16, getHeight() - 16, 16, 16);
    
    getProcessor().lastUIWidth = getWidth();
    getProcessor().lastUIHeight = getHeight();
}

//==============================================================================
void WavelandSynthAudioProcessorEditor::timerCallback()
{
    updateTimecodeDisplay (getProcessor().lastPosInfo);
}

//==============================================================================
// quick-and-dirty function to format a timecode string
static String timeToTimecodeString (double seconds)
{
    const int millisecs = roundToInt (std::abs (seconds * 1000.0));
    
    return String::formatted ("%s%02d:%02d:%02d.%03d",
                              seconds < 0 ? "-" : "",
                              millisecs / 360000,
                              (millisecs / 60000) % 60,
                              (millisecs / 1000) % 60,
                              millisecs % 1000);
}

// quick-and-dirty function to format a bars/beats string
static String quarterNotePositionToBarsBeatsString (double quarterNotes, int numerator, int denominator)
{
    if (numerator == 0 || denominator == 0)
        return "1|1|000";
    
    const int quarterNotesPerBar = (numerator * 4 / denominator);
    const double beats  = (fmod (quarterNotes, quarterNotesPerBar) / quarterNotesPerBar) * numerator;
    
    const int bar    = ((int) quarterNotes) / quarterNotesPerBar + 1;
    const int beat   = ((int) beats) + 1;
    const int ticks  = ((int) (fmod (beats, 1.0) * 960.0 + 0.5));
    
    return String::formatted ("%d|%d|%03d", bar, beat, ticks);
}

// Updates the text in our position label.
void WavelandSynthAudioProcessorEditor::updateTimecodeDisplay (AudioPlayHead::CurrentPositionInfo pos)
{
    if (lastDisplayedPosition != pos)
    {
        lastDisplayedPosition = pos;
        
        MemoryOutputStream displayText;
        
        displayText << "[" << SystemStats::getJUCEVersion() << "]   "
        << String (pos.bpm, 2) << " bpm, "
        << pos.timeSigNumerator << '/' << pos.timeSigDenominator
        << "  -  " << timeToTimecodeString (pos.timeInSeconds)
        << "  -  " << quarterNotePositionToBarsBeatsString (pos.ppqPosition,
                                                            pos.timeSigNumerator,
                                                            pos.timeSigDenominator);
        
        if (pos.isRecording)
            displayText << "  (recording)";
        else if (pos.isPlaying)
            displayText << "  (playing)";
        
        timecodeDisplayLabel.setText (displayText.toString(), dontSendNotification);
    }
}
